{
	"_Type": "Action.Type.PopoverMenu",
	"PopoverItems": [
		{
			"Enabled": true,
			"Icon": "sap-icon://refresh",
			"OnPress": "/LinkAuth/Actions/Application/AppUpdateProgressBanner.action",
			"Title": "Check for Updates",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://hint",
			"OnPress": "/LinkAuth/Actions/Application/NavToAbout.action",
			"Title": "About",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://reset",
			"OnPress": "/LinkAuth/Actions/Application/ResetMessage.action",
			"Title": "Reset",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://log",
			"OnPress": "/LinkAuth/Actions/Application/Logout.action",
			"Title": "Logout",
			"Visible": "/LinkAuth/Rules/Application/ClientIsMultiUserMode.js"
		},
		{
			"Title": "Documents",
			"Icon": "",
			"OnPress": "",
			"Visible": true,
			"Enabled": true,
			"TextAlignment": "Left",
			"Styles.Icon": "",
			"Styles": {
				"Title": "AuthenticateUsers"
			}
		}
	]
}