/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const generateauthtoken_Logic = require('./code/generateauthtoken-logic');

class SAPFoundryService extends LCAPApplicationService {
    async init() {

        // Register GenerateAuthToken as a bound action on ExternalPartners
        this.on('GenerateAuthToken', 'ExternalPartners', async (request) => {
            return generateauthtoken_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    SAPFoundryService
};